name: expense
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-47.0.dev <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  image_picker: ^1.0.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  gap: ^3.0.1
  intl: ^0.18.1
  provider: ^6.1.1
  firebase_storage: ^11.5.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Light.ttf
          weight: 300
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-Medium.ttf
          weight: 500
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/font/Manrope-Bold.ttf
          weight: 700
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 800
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/expense.png
  color_dark: "#ffffff"

  android_12:
    image: assets/images/expense.png
    icon_background_color: "#ffffff"

  web: false
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/expense.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

